### PR TITLE
[WIP] Migrate dotnet-Parser to .Net Core

### PR DESCRIPTION
**Pull request by SabotageAndi**
This PR migrates the existing dotnet parser, which is csproj based, to .NET Core RTM 1.0.1.
Additionally to the .NET 4.5 library, it now also compiles it for netstandard1.3 (https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms)

All tests are executed for the .NET 4.5 and .Netstandard1.3 version and are green.
Also I upgraded SpecFlow with a NuGet from this and there everything is also working.

Still open:
- ~~Travis-CI/AppVeyor changes that the parser gets build on it~~
- ~~probably updating some now outdated documentation~~

Known problems:
- ~~code signing: looks like it does not work on Mac OS X. I had to build on Windows to get a version that work in SpecFlow.~~

I created this not yet complete finished pull request 
- so that people do not make the work again
- review of the Makefile (I am not the best at make, it is working, but I think there are better solutions than mine)
- general feedback

### CODE REVIEW

**Comment by SabotageAndi** [comment]
AppVeyor/Travis-CI is now working.

**Comment by aslakhellesoy** [comment]
Sorry it's taken so long to get back to you about this @SabotageAndi.

Could you please rebase your PR branch and force-push? There are some conflicts in `appveyor.yml`.

Thanks!

**Comment by SabotageAndi** [comment]
@aslakhellesoy No problem, it is still work in progress.
I also didn't had the time yet to update it to .Net Core RTM.

I will work on it in the next weeks.

**Comment by aslakhellesoy** [comment]
Awesome - thanks!

**Comment by jmezach** [comment]
Any updates on this? Would love to have this available for .NET Core.

**Comment by SabotageAndi** [comment]
@jmezach Everything should work. Only the NuGet package creation is missing.

**Comment by jmezach** [comment]
@SabotageAndi Awesome! Shouldn't a dotnet pack be enough to get the NuGet package created?

**Comment by SabotageAndi** [comment]
@jmezach yes, but I am not sure, if the NuGet package is created with all information. I did not test it yet.
And I was not sure what will be the prefered way of creating NuGet packages, as the end of project.json was only a matter of time.

**Comment by jmezach** [comment]
@SabotageAndi Ah, I see. I just ran dotnet pack in my local clone after running the build through make and from what I can see all the necessary metadata is there.

As for the end of the project.json that is certainly something to consider. That said, migrating to the new format should be simple once the tools are final. And from what I can tell from the [announcement](https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/) post dotnet pack should work the same, except that it uses MSBuild to do the magic.

**Comment by SabotageAndi** [comment]
Cool, then I do not see any other showstopper for this PR.
I will try to finish it next week, so that we can also use it in SpecFlow for the .Net Core support.

**Comment by aslakhellesoy** [comment]
I usually release all languge packages simultaneously. Please update the release process docs if the release process has changed from previous releases.

Thanks

**Comment by aslakhellesoy** [comment]
How is it going guys?

**Comment by SabotageAndi** [comment]
I have this week exams, but I hope I can finish this finally after them.
As far as I remember, the last thing what is missing, is making the release- make target work again.

**Comment by sne-cloud** [comment]
Looking forward to the .Net core version, our team has kind of come to a halt because of this and might be forced to look for a different tool, which i would hate to do. 
Hope you will be publishing something soon, and again thanks for all your hard work.

**Comment by aslakhellesoy** [comment]
@SabotageAndi - do you have any suggestions how people can help to move this forward? Would you be interested in contributing @sne-cloud ?

**Comment by sne-cloud** [comment]
@aslakhellesoy @SabotageAndi  The guys in my team would like to contribute if possible

**Comment by SabotageAndi** [comment]
I think I have finished the release make target. Adjusting the documentation for releasing and some small testing is open and some adjustments to the build definitions.
I was looking forward to do this today in the evening.

@sne-cloud Help for testing the nuget would be helpful.

**Comment by jmezach** [comment]
@SabotageAndi I can help test this as well. We have a command line tool that uses this library to parse Gherkin files and I'm looking to port it to .NET Core so we can make it available cross-platform.

Can we get a pre-release up on NuGet.org perhaps? That would be the easiest way anyway.

**Comment by SabotageAndi** [comment]
make update-version should working now.
Merging current master branch gave me some headache. I am not sure if everything is correct now. 
CI Build definitions are still open.
I am looking to work on them tomorrow (2th February).

**Comment by SabotageAndi** [comment]
CI Build definitions are now working again.
I was also able to speed up the testrun.

@aslakhellesoy Could you have a look at the Makefile? I am not sure if I did all in the best way possible.

@jmezach @sne-cloud You can find a NuGet for testing in the artefacts of the appveyor build (https://ci.appveyor.com/project/aslakhellesoy/gherkin/build/1.0.151/artifacts).
I updated SpecFlow to this NuGet and everything was still working.

**Comment by aslakhellesoy** [comment]
Thanks for your hard work on this @SabotageAndi!

I'm trying to build this. Looks like `dotnet/Gherkin.CSharp.sln` has been badly merged.

What's the recommended way to install the `dotnet` command line on OS X? There doesn't appear to be a working Homebrew formula, see dotnet/cli#533. Download from [here](https://github.com/dotnet/core/blob/master/release-notes/rc3-download.md)?

**Comment by aslakhellesoy** [comment]
Since the `.sln` is corrupted I tried to create one from scratch using Visual Studio for Mac - Version Preview 3 (7.0 build 1077). That doesn't appear to support `.xproj` files, only `.csproj`.

Building Gherkin.NET on Mac/Linux has worked fine on master, but with this change I'm not sure anymore.

Can you confirm whether this will be possible, and what tools need to be installed to do so?

**Comment by SabotageAndi** [comment]
@aslakhellesoy You get .NET Core from here: https://www.microsoft.com/net/download/core
I updated the project to the latest LTS version.

About the solution/sln file: I used VS Code with the C# plugin and a terminal to work on it. 
Tooling support for .NET Core was never the best in XamarinStudio/Visual Studio for Mac. 
In the last weeks/months, they changed it again from project.json/xproj back to csproj. But this is not yet finished and they are still changing stuff. 

I could upgrade to the new project format, but probably there will be changes needed in the future to make it work again.

**Comment by aslakhellesoy** [comment]
Thanks for the pointers and clarification @SabotageAndi!

Could you please fix the corrupt `.sln` file in a new commit so I can try it out?

**Comment by aslakhellesoy** [comment]
I'm hoping to do a new Gherkin release on Friday (I spend most Fridays on open source work).

If the corrupt `.sln` file has been fixed an pushes to this PR's branch by then I might be able to include this in the release!

I've even got a Windows box handy in case I can't build it on Linux and/or OS X.

**Comment by mwadams** [comment]
Just as a heads up - that builds successfully in VS 2017, and all tests pass.

**Comment by aslakhellesoy** [comment]
> Just as a heads up - that builds successfully in VS 2017, and all tests pass.

@mwadams - did you add this comment and delete it shortly after? (GitHub told me there was a new comment in this issue, but it seems to be gone).

Anyway, how are you able to build this PR? The `.sln` file is still [corrupt](https://github.com/SabotageAndi/gherkin/blob/03ce53bfb3246ceac2e4bfe149ecf84179462545/dotnet/Gherkin.CSharp.sln#L12-L30).

**Comment by SabotageAndi** [comment]
I had no time to fix it yet. 
As VS2017 will be released at the 7th of March, I was thinking about doing the migration to the new project system before merging merging into master.

**Comment by mwadams** [comment]
Hi -

Yes - I did. I have a build locally using the latest VS 2017 bits / csproj files (that shouldn't need any migration from the March 17th shipping version.

The assemblies Gherkin and Gherkin.TokenGenerator are targeting NetStandard1.3 and the Specs and the CLI projects are targeting NetCore1.1.

I paused and deleted the comment because I have not added the Net451 targets back into the latter two items.

**Comment by mwadams** [comment]
Quick question before I fork - were you overriding any of the output directories? It all looks pretty "default", but just in case!

**Comment by mwadams** [comment]
OK - well, I've pushed it up on my fork; the AppVeyor  build is, I assume, using older dotnet tooling

**Comment by mwadams** [comment]
Looks like AppVeyor doesn't yet support VS2017 tooling, so we're in limbo.

**Comment by SabotageAndi** [comment]
@mwadams It is in private beta: https://github.com/appveyor/ci/issues/1179
You can request access to it. I have enabled it, so it should work with your PR. When I merge the changes to this PR, @aslakhellesoy has to request it for him, because the AppVeyor build runs under his name.

To get it to build with VS2017, have a look at this appveyor.yml: https://github.com/techtalk/SpecFlow.VisualStudio/blob/master/appveyor.yml.
Remove the os and add the image setting.

**Comment by mwadams** [comment]
Great job @SabotageAndi

**Comment by aslakhellesoy** [comment]
Yeah, seconded. I made some minor changes in 54648d320ee17eaff9a077dbe6d40667c94e2459 in order to make the build pass on OS X.

I still haven't managed to build an executable that runs. I'll tinker with it some more. If I can't make it build on OS X/Linux, we can always make releases on a Windows machine.

Maybe I'll ask for private beta access to Appveyor's Visual Studio 2017 RC support - seems to be taking a while.

**Comment by SabotageAndi** [comment]
@aslakhellesoy the problem with your changes are, that we are targeting .NET 4.5 in SpecFlow and so we need the Gherkin parser also for .NET 4.5.
Sadly with the version before RTM (which did go live yesterday) I was not able to build .NET 4.5 stuff on my Mac. It simply does not know how to compile it.

I have to recheck this with the RTM version. If it is not working, I have to think about another solution.
Targeting .NET Standard 1.5 is sadly no option, because that is .NET 4.6.2 API level.

If you want to make a release, I would not wait on this PR. Could be a little bit more work.

**Comment by aslakhellesoy** [comment]
@SabotageAndi the lines I commented out in `dotnet/Makefile` are temporary while I'm figuring out how to make this work on Mac. I intend to have some kind of branching logic there so that net45 is still built when building on Windows.

The reason I added netstandard as a target is that it seemed to work better on Mac.

I'll have to play around with it some more.

**Comment by aslakhellesoy** [comment]
I've merged this to master, with some changes to make this build on my OSX dev machine. I'm in the process of migrating this repo over to the cucumber/cucumber monorepo (see https://groups.google.com/forum/#!topic/cukes-devs/RmxWretSW_g).

Part of the goal of this migration is to improve CI. Every subrepo will have its own CI build rather than defining the build in the parent directory like [this](https://github.com/cucumber/gherkin/blob/master/.travis.yml) and [this](https://github.com/cucumber/gherkin/blob/master/appveyor.yml)

I know there are probably some more tweaks needed to make this build properly on Windows dev machines and Appveyor, as well as making releases.

Please don't make any more pull requests against this repo to address that. Instead, wait until the migration to monorepo is done so we can carry on there.

**Comment by SabotageAndi** [comment]
Ok. Where can I see when the migration to the monorepo is finished?

**Comment by aslakhellesoy** [comment]
I'll post a notification to the cukes google group. I'll also close all issues in this repo and delete files on master except README which will point to the new location.

**Comment by aslakhellesoy** [comment]
I'll also notify on https://gitter.im/cucumber/contributors

Anywhere else I should send notifications?

**Comment by SabotageAndi** [comment]
@aslakhellesoy No, they are fine.

**Comment by aslakhellesoy** [comment]
Hi @SabotageAndi - we've moved!

You'll find the code over [here](https://github.com/cucumber/cucumber/tree/master/gherkin/dotnet)

**Comment by jmezach** [comment]
@SabotageAndi What's the status of this? I know this is merged because of the move, but it seems that the builds are failing there. Is there another issue tracking this? Anything I can help with? Would love to move this along.

**Comment by SabotageAndi** [comment]
@jmezach I created a moment ago a new PR (https://github.com/cucumber/cucumber/pull/174) to finish this stuff.

**Pull request merged**
